---

- name: restart httpd
  service: >-
    name=httpd
    state=restarted
    enabled=yes
  when: "ansible_os_family == 'RedHat'"
  
- name: restart httpd
  service: >-
    name=apache2
    state=restarted
    enabled=yes
  when: "ansible_os_family == 'Debian'"

- name: restart gmetad
  service: >-
    name=gmetad
    state=restarted
    enabled=yes

